#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openQA
Version  : 4.6.7a262516
Release  : 12
URL      : https://github.com/os-autoinst/openQA/archive/7a262516c4cac633835273c3bb2a01eb1a3df2a8/openQA-7a262516c4cac633835273c3bb2a01eb1a3df2a8.tar.gz
Source0  : https://github.com/os-autoinst/openQA/archive/7a262516c4cac633835273c3bb2a01eb1a3df2a8/openQA-7a262516c4cac633835273c3bb2a01eb1a3df2a8.tar.gz
Source1  : http://localhost/cgit/projects/openQA-dep/snapshot/openQA-dep-latest.tar.gz
Summary  : The openQA web-frontend, scheduler and tools
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: openQA-config = %{version}-%{release}
Requires: openQA-data = %{version}-%{release}
Requires: openQA-license = %{version}-%{release}
Requires: openQA-services = %{version}-%{release}
Requires: perl-Archive-Extract
Requires: perl-B-Hooks-EndOfScope
Requires: perl-BSD-Resource
Requires: perl-CGI
Requires: perl-CSS-Minifier-XS
Requires: perl-Carp-Clan
Requires: perl-Class-Accessor-Grouped
Requires: perl-Class-C3-Componentised
Requires: perl-Class-Data-Inheritable
Requires: perl-Class-Factory-Util
Requires: perl-Class-Load
Requires: perl-Class-Method-Modifiers
Requires: perl-Class-Singleton
Requires: perl-Clone-Choose
Requires: perl-Config-IniFiles
Requires: perl-Config-Tiny
Requires: perl-Context-Preserve
Requires: perl-Cpanel-JSON-XS
Requires: perl-Crypt-DH-GMP
Requires: perl-DBD-Pg
Requires: perl-DBIx-Class
Requires: perl-DBIx-Class-DeploymentHandler
Requires: perl-DBIx-Class-DynamicDefault
Requires: perl-DBIx-Class-OptimisticLocking
Requires: perl-DBIx-Class-Schema-Config
Requires: perl-Data-Dump
Requires: perl-Data-Dump-dev
Requires: perl-Data-Dumper-Concise
Requires: perl-Data-OptList
Requires: perl-DateTime
Requires: perl-DateTime-Format-Builder
Requires: perl-DateTime-Format-MySQL
Requires: perl-DateTime-Format-Pg
Requires: perl-DateTime-Format-Strptime
Requires: perl-DateTime-Locale
Requires: perl-Devel-GlobalDestruction
Requires: perl-Devel-OverloadInfo
Requires: perl-Devel-StackTrace
Requires: perl-Devel-Symdump
Requires: perl-Eval-Closure
Requires: perl-Exception-Class
Requires: perl-Exporter-Declare
Requires: perl-File-Copy-Recursive
Requires: perl-File-ShareDir
Requires: perl-Hash-Merge
Requires: perl-IO-Socket-SSL
Requires: perl-IPC-Run
Requires: perl-IPC-Run3
Requires: perl-Import-Into
Requires: perl-JSON
Requires: perl-JavaScript-Minifier-XS
Requires: perl-Log-Contextual
Requires: perl-MRO-Compat
Requires: perl-Meta-Builder
Requires: perl-Minion
Requires: perl-Module-Find
Requires: perl-Module-Implementation
Requires: perl-Module-Runtime
Requires: perl-Mojo-IOLoop-ReadWriteProcess
Requires: perl-Mojo-Pg
Requires: perl-Mojo-RabbitMQ-Client
Requires: perl-Mojolicious
Requires: perl-Mojolicious-Plugin-AssetPack
Requires: perl-Mojolicious-Plugin-RenderFile
Requires: perl-Moo
Requires: perl-Moose
Requires: perl-MooseX-Role-Parameterized
Requires: perl-Net-DBus
Requires: perl-Net-OpenID-Common
Requires: perl-Net-OpenID-Consumer
Requires: perl-Package-DeprecationManager
Requires: perl-Package-Stash
Requires: perl-Package-Variant
Requires: perl-Params-ValidationCompiler
Requires: perl-Path-Class
Requires: perl-Pod-Coverage
Requires: perl-Pod-POM
Requires: perl-Pod-POM-bin
Requires: perl-Regexp-Common
Requires: perl-Role-Tiny
Requires: perl-SQL-Abstract
Requires: perl-SQL-Translator
Requires: perl-Socket-MsgHdr
Requires: perl-Sort-Versions
Requires: perl-Sub-Exporter
Requires: perl-Sub-Exporter-Progressive
Requires: perl-Sub-Identify
Requires: perl-Sub-Name
Requires: perl-Sub-Quote
Requires: perl-Test-Compile
Requires: perl-Text-Markdown
Requires: perl-Time-ParseDate
Requires: perl-Variable-Magic
Requires: perl-XML-Twig
Requires: perl-aliased
Requires: perl-namespace-autoclean
Requires: perl-namespace-clean
Requires: perl-strictures
BuildRequires : perl-Archive-Extract
BuildRequires : perl-B-Hooks-EndOfScope
BuildRequires : perl-BSD-Resource
BuildRequires : perl-CGI
BuildRequires : perl-CSS-Minifier-XS
BuildRequires : perl-Carp-Clan
BuildRequires : perl-Class-Accessor-Grouped
BuildRequires : perl-Class-C3-Componentised
BuildRequires : perl-Class-Data-Inheritable
BuildRequires : perl-Class-Factory-Util
BuildRequires : perl-Class-Load
BuildRequires : perl-Class-Method-Modifiers
BuildRequires : perl-Class-Singleton
BuildRequires : perl-Clone-Choose
BuildRequires : perl-Config-IniFiles
BuildRequires : perl-Config-Tiny
BuildRequires : perl-Context-Preserve
BuildRequires : perl-Cpanel-JSON-XS
BuildRequires : perl-Crypt-DH-GMP
BuildRequires : perl-DBD-Pg
BuildRequires : perl-DBIx-Class
BuildRequires : perl-DBIx-Class-DeploymentHandler
BuildRequires : perl-DBIx-Class-DynamicDefault
BuildRequires : perl-DBIx-Class-OptimisticLocking
BuildRequires : perl-DBIx-Class-Schema-Config
BuildRequires : perl-Data-Dump
BuildRequires : perl-Data-Dumper-Concise
BuildRequires : perl-Data-OptList
BuildRequires : perl-DateTime
BuildRequires : perl-DateTime-Format-Builder
BuildRequires : perl-DateTime-Format-MySQL
BuildRequires : perl-DateTime-Format-Pg
BuildRequires : perl-DateTime-Format-Strptime
BuildRequires : perl-DateTime-Locale
BuildRequires : perl-Devel-GlobalDestruction
BuildRequires : perl-Devel-OverloadInfo
BuildRequires : perl-Devel-StackTrace
BuildRequires : perl-Devel-Symdump
BuildRequires : perl-Eval-Closure
BuildRequires : perl-Exception-Class
BuildRequires : perl-Exporter-Declare
BuildRequires : perl-File-Copy-Recursive
BuildRequires : perl-File-ShareDir
BuildRequires : perl-Hash-Merge
BuildRequires : perl-IO-Socket-SSL
BuildRequires : perl-IPC-Run
BuildRequires : perl-IPC-Run3
BuildRequires : perl-Import-Into
BuildRequires : perl-JSON
BuildRequires : perl-JavaScript-Minifier-XS
BuildRequires : perl-Log-Contextual
BuildRequires : perl-MRO-Compat
BuildRequires : perl-Meta-Builder
BuildRequires : perl-Minion
BuildRequires : perl-Module-Find
BuildRequires : perl-Module-Implementation
BuildRequires : perl-Module-Runtime
BuildRequires : perl-Mojo-IOLoop-ReadWriteProcess
BuildRequires : perl-Mojo-Pg
BuildRequires : perl-Mojo-RabbitMQ-Client
BuildRequires : perl-Mojolicious
BuildRequires : perl-Mojolicious-Plugin-AssetPack
BuildRequires : perl-Mojolicious-Plugin-RenderFile
BuildRequires : perl-Moo
BuildRequires : perl-Moose
BuildRequires : perl-MooseX-Role-Parameterized
BuildRequires : perl-Net-DBus
BuildRequires : perl-Net-OpenID-Common
BuildRequires : perl-Net-OpenID-Consumer
BuildRequires : perl-Package-DeprecationManager
BuildRequires : perl-Package-Stash
BuildRequires : perl-Package-Variant
BuildRequires : perl-Params-ValidationCompiler
BuildRequires : perl-Path-Class
BuildRequires : perl-Pod-Coverage
BuildRequires : perl-Pod-POM
BuildRequires : perl-Regexp-Common
BuildRequires : perl-Role-Tiny
BuildRequires : perl-SQL-Abstract
BuildRequires : perl-SQL-Translator
BuildRequires : perl-Socket-MsgHdr
BuildRequires : perl-Sort-Versions
BuildRequires : perl-Sub-Exporter
BuildRequires : perl-Sub-Exporter-Progressive
BuildRequires : perl-Sub-Identify
BuildRequires : perl-Sub-Name
BuildRequires : perl-Sub-Quote
BuildRequires : perl-Test-Compile
BuildRequires : perl-Text-Markdown
BuildRequires : perl-Time-ParseDate
BuildRequires : perl-Variable-Magic
BuildRequires : perl-XML-Twig
BuildRequires : perl-aliased
BuildRequires : perl-namespace-autoclean
BuildRequires : perl-namespace-clean
BuildRequires : perl-strictures
Patch1: 0001-stateless.patch
Patch2: 0002-Update-tmpfiles-to-account-for-stateless-configurati.patch

%description
openQA is a testing framework that allows you to test GUI applications on one
hand and bootloader and kernel on the other. In both cases, it is difficult to
script tests and verify the output. Output can be a popup window or it can be
an error in early boot even before init is executed.

openQA is an automated test tool that makes it possible to test the whole
installation process of an operating system. It uses virtual machines to
reproduce the process, check the output (both serial console and screen) in
every step and send the necessary keystrokes and commands to proceed to the
next. openQA can check whether the system can be installed, whether it works
properly in 'live' mode, whether applications work or whether the system
responds as expected to different installation options and commands.

Even more importantly, openQA can run several combinations of tests for every
revision of the operating system, reporting the errors detected for each
combination of hardware configuration, installation options and variant of the
operating system.

%package config
Summary: config components for the openQA package.
Group: Default

%description config
config components for the openQA package.


%package data
Summary: data components for the openQA package.
Group: Data

%description data
data components for the openQA package.


%package license
Summary: license components for the openQA package.
Group: Default

%description license
license components for the openQA package.


%package services
Summary: services components for the openQA package.
Group: Systemd services

%description services
services components for the openQA package.


%prep
%setup -q -n openQA-7a262516c4cac633835273c3bb2a01eb1a3df2a8
cd ..
%setup -q -T -D -n openQA-7a262516c4cac633835273c3bb2a01eb1a3df2a8 -b 1
mkdir -p assets
cp -r %{_topdir}/BUILD/openQA-dep-latest/* %{_topdir}/BUILD/openQA-7a262516c4cac633835273c3bb2a01eb1a3df2a8/assets
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1564620760
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1564620760
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openQA
cp COPYING %{buildroot}/usr/share/package-licenses/openQA/COPYING
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/systemd/system-generators/systemd-openqa-generator

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/openqa.conf

%files data
%defattr(-,root,root,-)
/usr/share/examples/openqa/apache2/vhosts.d/openqa-common.inc
/usr/share/examples/openqa/apache2/vhosts.d/openqa-ssl.conf.template
/usr/share/examples/openqa/apache2/vhosts.d/openqa.conf.template
/usr/share/examples/openqa/client.conf
/usr/share/examples/openqa/database.ini
/usr/share/examples/openqa/openqa.ini
/usr/share/examples/openqa/workers.ini
/usr/share/openqa/assets/assetpack.db
/usr/share/openqa/assets/assetpack.def
/usr/share/openqa/assets/cache/admin_assets-6051ee1b3d.min.js
/usr/share/openqa/assets/cache/admin_groups-6cdb6822a2.min.js
/usr/share/openqa/assets/cache/admin_needle-8341c3d15f.min.js
/usr/share/openqa/assets/cache/admin_user-c434ec3c2a.min.js
/usr/share/openqa/assets/cache/admin_worker-20448e44f5.min.js
/usr/share/openqa/assets/cache/admintable-bb08263ec6.min.js
/usr/share/openqa/assets/cache/all-cf92156deb.min.css
/usr/share/openqa/assets/cache/audit_log-aabd7c6f33.min.js
/usr/share/openqa/assets/cache/bootstrap-12c49f4247.min.js
/usr/share/openqa/assets/cache/bootstrap-4-navbar-4245576e49.min.js
/usr/share/openqa/assets/cache/bootstrap-4-navbar-52bb9cdce1.min.css
/usr/share/openqa/assets/cache/bootstrap-tour-0429df1368.min.css
/usr/share/openqa/assets/cache/cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.css
/usr/share/openqa/assets/cache/cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.js
/usr/share/openqa/assets/cache/cdn.datatables.net/1.10.16/js/jquery.dataTables.js
/usr/share/openqa/assets/cache/cdnjs.cloudflare.com/ajax/libs/chosen/1.7.0/chosen-sprite.png
/usr/share/openqa/assets/cache/cdnjs.cloudflare.com/ajax/libs/chosen/1.7.0/chosen-sprite@2x.png
/usr/share/openqa/assets/cache/cdnjs.cloudflare.com/ajax/libs/chosen/1.7.0/chosen.css
/usr/share/openqa/assets/cache/cdnjs.cloudflare.com/ajax/libs/chosen/1.7.0/chosen.jquery.js
/usr/share/openqa/assets/cache/cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.1/rails.js
/usr/share/openqa/assets/cache/cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.js
/usr/share/openqa/assets/cache/cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.js.map
/usr/share/openqa/assets/cache/chosen-1b5d75fd60.min.css
/usr/share/openqa/assets/cache/chosen.jquery-3d255efbd2.min.js
/usr/share/openqa/assets/cache/code.jquery.com/jquery-3.3.1.js
/usr/share/openqa/assets/cache/codemirror-aa7c7a96d3.min.css
/usr/share/openqa/assets/cache/codemirror-fa2da57c92.min.js
/usr/share/openqa/assets/cache/codemirror_customization-32d2c7d0af.min.css
/usr/share/openqa/assets/cache/comments-fd70a709b5.min.js
/usr/share/openqa/assets/cache/d3.v4-9110f0589d.min.js
/usr/share/openqa/assets/cache/d3js.org/d3.v4.js
/usr/share/openqa/assets/cache/dagre-d3-a6b809edea.min.js
/usr/share/openqa/assets/cache/dataTables.bootstrap4-0251e508b2.min.js
/usr/share/openqa/assets/cache/dataTables.bootstrap4-9b113d6424.min.css
/usr/share/openqa/assets/cache/dependency_graph-7bde0baf3f.css
/usr/share/openqa/assets/cache/dependency_graph-7bde0baf3f.min.css
/usr/share/openqa/assets/cache/disable_animations-528b393467.min.js
/usr/share/openqa/assets/cache/feature-54a516ee76.min.js
/usr/share/openqa/assets/cache/filter_form-956ff8b3ba.min.js
/usr/share/openqa/assets/cache/fullscreen-cabe45067b.min.js
/usr/share/openqa/assets/cache/index-faf8a76672.min.js
/usr/share/openqa/assets/cache/job_next_previous-635281fa3e.min.js
/usr/share/openqa/assets/cache/job_templates-142a8d4c53.min.js
/usr/share/openqa/assets/cache/jquery-3.3.1-23d894426e.min.js
/usr/share/openqa/assets/cache/jquery.dataTables-5f1e9c27ae.min.js
/usr/share/openqa/assets/cache/jquery.timeago-8752fc496f.min.js
/usr/share/openqa/assets/cache/keyevent-590865e808.min.js
/usr/share/openqa/assets/cache/maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.js
/usr/share/openqa/assets/cache/maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.js.map
/usr/share/openqa/assets/cache/needlediff-d5af99e8a7.min.js
/usr/share/openqa/assets/cache/needleeditor-e88a660733.min.js
/usr/share/openqa/assets/cache/openqa-11c05faa4e.css
/usr/share/openqa/assets/cache/openqa-11c05faa4e.min.css
/usr/share/openqa/assets/cache/openqa-ddb12c1440.min.js
/usr/share/openqa/assets/cache/overview-b07e1ef210.min.js
/usr/share/openqa/assets/cache/perl-2698ecafac.min.js
/usr/share/openqa/assets/cache/popper-aeda8ebd73.min.js
/usr/share/openqa/assets/cache/rails-31ef5a6799.min.js
/usr/share/openqa/assets/cache/raw.githubusercontent.com/bootstrapthemesco/bootstrap-4-multi-dropdown-navbar/beta2.0/css/bootstrap-4-navbar.css
/usr/share/openqa/assets/cache/raw.githubusercontent.com/bootstrapthemesco/bootstrap-4-multi-dropdown-navbar/beta2.0/js/bootstrap-4-navbar.js
/usr/share/openqa/assets/cache/raw.githubusercontent.com/codemirror/CodeMirror/8097c7e75ce7ef0512debe9967d7568626106e53/lib/codemirror.css
/usr/share/openqa/assets/cache/raw.githubusercontent.com/codemirror/CodeMirror/8097c7e75ce7ef0512debe9967d7568626106e53/lib/codemirror.js
/usr/share/openqa/assets/cache/raw.githubusercontent.com/codemirror/CodeMirror/8097c7e75ce7ef0512debe9967d7568626106e53/mode/perl/perl.js
/usr/share/openqa/assets/cache/raw.githubusercontent.com/codemirror/CodeMirror/8097c7e75ce7ef0512debe9967d7568626106e53/mode/yaml/yaml.js
/usr/share/openqa/assets/cache/raw.githubusercontent.com/dagrejs/dagre-d3/v0.5.0/dist/dagre-d3.js
/usr/share/openqa/assets/cache/raw.githubusercontent.com/sorich87/bootstrap-tour/6a1028fb562f9aa68c451f0901f8cfeb43cad140/build/css/bootstrap-tour.css
/usr/share/openqa/assets/cache/raw.githubusercontent.com/sorich87/bootstrap-tour/6a1028fb562f9aa68c451f0901f8cfeb43cad140/build/js/bootstrap-tour.min.js
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_alert.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_badge.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_breadcrumb.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_button-group.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_buttons.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_card.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_carousel.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_close.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_code.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_custom-forms.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_dropdown.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_forms.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_functions.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_grid.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_images.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_input-group.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_jumbotron.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_list-group.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_media.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_mixins.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_modal.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_nav.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_navbar.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_pagination.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_popover.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_print.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_progress.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_reboot.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_root.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_tables.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_tooltip.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_transitions.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_type.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_utilities.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/_variables.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/bootstrap.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_alert.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_background-variant.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_badge.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_border-radius.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_box-shadow.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_breakpoints.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_buttons.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_caret.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_clearfix.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_float.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_forms.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_gradients.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_grid-framework.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_grid.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_hover.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_image.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_list-group.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_lists.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_nav-divider.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_pagination.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_reset-text.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_resize.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_screen-reader.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_size.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_table-row.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_text-emphasis.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_text-hide.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_text-truncate.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_transition.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/mixins/_visibility.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_align.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_background.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_borders.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_clearfix.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_display.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_embed.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_flex.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_float.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_position.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_screenreaders.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_shadows.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_sizing.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_spacing.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_text.scss
/usr/share/openqa/assets/cache/raw.githubusercontent.com/twbs/bootstrap/v4.1.1/scss/utilities/_visibility.scss
/usr/share/openqa/assets/cache/running-b156b39ab7.min.js
/usr/share/openqa/assets/cache/shapes-90ed81a726.min.js
/usr/share/openqa/assets/cache/test_result-b2db3d0c9a.min.js
/usr/share/openqa/assets/cache/tests-18f8be5de9.min.js
/usr/share/openqa/assets/cache/timeago.yarp.com/jquery.timeago.js
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/css/all.css
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-brands-400.eot
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-brands-400.svg
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-brands-400.ttf
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-brands-400.woff2
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-regular-400.eot
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-regular-400.svg
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-regular-400.ttf
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-regular-400.woff2
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-solid-900.eot
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-solid-900.svg
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-solid-900.ttf
/usr/share/openqa/assets/cache/use.fontawesome.com/releases/v5.0.10/webfonts/fa-solid-900.woff2
/usr/share/openqa/assets/cache/ws_console-37bbd17108.min.js
/usr/share/openqa/assets/cache/ws_console-5a086c2a3a.css
/usr/share/openqa/assets/cache/ws_console-5a086c2a3a.min.css
/usr/share/openqa/assets/cache/yaml-671a17d97b.min.js
/usr/share/openqa/assets/images/audio.svg
/usr/share/openqa/assets/images/logo-16.png
/usr/share/openqa/assets/images/logo.svg
/usr/share/openqa/assets/images/suse.png
/usr/share/openqa/assets/images/terminal.svg
/usr/share/openqa/assets/javascripts/admin_assets.js
/usr/share/openqa/assets/javascripts/admin_groups.js
/usr/share/openqa/assets/javascripts/admin_needle.js
/usr/share/openqa/assets/javascripts/admin_user.js
/usr/share/openqa/assets/javascripts/admin_worker.js
/usr/share/openqa/assets/javascripts/admintable.js
/usr/share/openqa/assets/javascripts/audit_log.js
/usr/share/openqa/assets/javascripts/comments.js
/usr/share/openqa/assets/javascripts/disable_animations.js
/usr/share/openqa/assets/javascripts/feature.js
/usr/share/openqa/assets/javascripts/filter_form.js
/usr/share/openqa/assets/javascripts/fullscreen.js
/usr/share/openqa/assets/javascripts/index.js
/usr/share/openqa/assets/javascripts/job_next_previous.js
/usr/share/openqa/assets/javascripts/job_templates.js
/usr/share/openqa/assets/javascripts/keyevent.js
/usr/share/openqa/assets/javascripts/needlediff.js
/usr/share/openqa/assets/javascripts/needleeditor.js
/usr/share/openqa/assets/javascripts/openqa.js
/usr/share/openqa/assets/javascripts/overview.js
/usr/share/openqa/assets/javascripts/running.js
/usr/share/openqa/assets/javascripts/scheduler.js
/usr/share/openqa/assets/javascripts/shapes.js
/usr/share/openqa/assets/javascripts/test_result.js
/usr/share/openqa/assets/javascripts/tests.js
/usr/share/openqa/assets/javascripts/ws_console.js
/usr/share/openqa/assets/stylesheets/admin-pages.scss
/usr/share/openqa/assets/stylesheets/bootswatch_litera_theme.scss
/usr/share/openqa/assets/stylesheets/codemirror_customization.css
/usr/share/openqa/assets/stylesheets/comments.scss
/usr/share/openqa/assets/stylesheets/cropper.css
/usr/share/openqa/assets/stylesheets/dashboard.scss
/usr/share/openqa/assets/stylesheets/dependency_graph.scss
/usr/share/openqa/assets/stylesheets/forms.scss
/usr/share/openqa/assets/stylesheets/navigation.scss
/usr/share/openqa/assets/stylesheets/openqa.scss
/usr/share/openqa/assets/stylesheets/openqa_theme.scss
/usr/share/openqa/assets/stylesheets/overall.scss
/usr/share/openqa/assets/stylesheets/overview.scss
/usr/share/openqa/assets/stylesheets/result_preview.scss
/usr/share/openqa/assets/stylesheets/tables.scss
/usr/share/openqa/assets/stylesheets/test-details.scss
/usr/share/openqa/assets/stylesheets/ws_console.scss
/usr/share/openqa/dbicdh/PostgreSQL/deploy/63/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/63/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/64/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/64/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/65/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/65/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/66/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/66/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/67/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/67/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/68/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/68/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/69/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/69/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/70/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/70/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/71/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/71/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/72/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/72/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/73/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/73/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/74/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/74/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/75/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/75/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/76/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/76/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/77/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/77/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/78/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/78/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/79/001-auto-__VERSION.sql
/usr/share/openqa/dbicdh/PostgreSQL/deploy/79/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/63-64/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/63-64/002-update.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/64-65/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/65-66/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/66-67/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/67-68/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/68-69/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/69-70/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/70-71/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/71-72/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/72-73/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/73-74/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/74-75/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/75-76/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/76-77/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/77-78/001-auto.sql
/usr/share/openqa/dbicdh/PostgreSQL/upgrade/78-79/001-auto.sql
/usr/share/openqa/dbicdh/_common/upgrade/65-66/001-migrate-jobs.pl
/usr/share/openqa/dbicdh/_common/upgrade/69-70/001-set-finished-and-fix-state.pl
/usr/share/openqa/dbicdh/_common/upgrade/76-77/001-migrate-audit-events-to-scheduled-products.pl
/usr/share/openqa/dbicdh/_source/deploy/63/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/63/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/64/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/64/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/65/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/65/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/66/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/66/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/67/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/67/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/68/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/68/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/69/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/69/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/70/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/70/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/71/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/71/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/72/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/72/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/73/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/73/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/74/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/74/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/75/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/75/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/76/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/76/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/77/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/77/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/78/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/78/001-auto.yml
/usr/share/openqa/dbicdh/_source/deploy/79/001-auto-__VERSION.yml
/usr/share/openqa/dbicdh/_source/deploy/79/001-auto.yml
/usr/share/openqa/lib/DBIx/Class/Timestamps.pm
/usr/share/openqa/lib/OpenQA.pm
/usr/share/openqa/lib/OpenQA/BuildResults.pm
/usr/share/openqa/lib/OpenQA/Client.pm
/usr/share/openqa/lib/OpenQA/Client/Archive.pm
/usr/share/openqa/lib/OpenQA/Client/Handler.pm
/usr/share/openqa/lib/OpenQA/Client/Upload.pm
/usr/share/openqa/lib/OpenQA/Constants.pm
/usr/share/openqa/lib/OpenQA/Events.pm
/usr/share/openqa/lib/OpenQA/ExpandPlaceholder.pm
/usr/share/openqa/lib/OpenQA/File.pm
/usr/share/openqa/lib/OpenQA/Git.pm
/usr/share/openqa/lib/OpenQA/JobDependencies/Constants.pm
/usr/share/openqa/lib/OpenQA/Jobs/Constants.pm
/usr/share/openqa/lib/OpenQA/LiveHandler.pm
/usr/share/openqa/lib/OpenQA/Parser.pm
/usr/share/openqa/lib/OpenQA/Parser/Format/Base.pm
/usr/share/openqa/lib/OpenQA/Parser/Format/IPA.pm
/usr/share/openqa/lib/OpenQA/Parser/Format/JUnit.pm
/usr/share/openqa/lib/OpenQA/Parser/Format/LTP.pm
/usr/share/openqa/lib/OpenQA/Parser/Format/TAP.pm
/usr/share/openqa/lib/OpenQA/Parser/Format/XUnit.pm
/usr/share/openqa/lib/OpenQA/Parser/Result.pm
/usr/share/openqa/lib/OpenQA/Parser/Result/Node.pm
/usr/share/openqa/lib/OpenQA/Parser/Result/OpenQA.pm
/usr/share/openqa/lib/OpenQA/Parser/Result/OpenQA/Results.pm
/usr/share/openqa/lib/OpenQA/Parser/Result/Output.pm
/usr/share/openqa/lib/OpenQA/Parser/Result/Test.pm
/usr/share/openqa/lib/OpenQA/Parser/Results.pm
/usr/share/openqa/lib/OpenQA/Resource/Jobs.pm
/usr/share/openqa/lib/OpenQA/Resource/Locks.pm
/usr/share/openqa/lib/OpenQA/Scheduler.pm
/usr/share/openqa/lib/OpenQA/Scheduler/Client.pm
/usr/share/openqa/lib/OpenQA/Scheduler/Controller/API.pm
/usr/share/openqa/lib/OpenQA/Scheduler/Model/Jobs.pm
/usr/share/openqa/lib/OpenQA/Schema.pm
/usr/share/openqa/lib/OpenQA/Schema/JobGroupDefaults.pm
/usr/share/openqa/lib/OpenQA/Schema/Profiler.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/ApiKeys.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Assets.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/AuditEvents.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Bugs.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Comments.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/DeveloperSessions.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/GruDependencies.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/GruTasks.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobDependencies.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobGroupParents.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobGroups.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobLocks.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobModules.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobNetworks.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobNextPrevious.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobSettings.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobTemplateSettings.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobTemplates.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Jobs.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/JobsAssets.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/MachineSettings.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Machines.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/NeedleDirs.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Needles.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/ProductSettings.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Products.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/ScheduledProducts.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/ScreenshotLinks.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Screenshots.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Secrets.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/TestSuiteSettings.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/TestSuites.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Users.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/WorkerProperties.pm
/usr/share/openqa/lib/OpenQA/Schema/Result/Workers.pm
/usr/share/openqa/lib/OpenQA/Schema/ResultSet/Assets.pm
/usr/share/openqa/lib/OpenQA/Schema/ResultSet/Bugs.pm
/usr/share/openqa/lib/OpenQA/Schema/ResultSet/DeveloperSessions.pm
/usr/share/openqa/lib/OpenQA/Schema/ResultSet/JobSettings.pm
/usr/share/openqa/lib/OpenQA/Schema/ResultSet/Jobs.pm
/usr/share/openqa/lib/OpenQA/Schema/ResultSet/Needles.pm
/usr/share/openqa/lib/OpenQA/Schema/ResultSet/Users.pm
/usr/share/openqa/lib/OpenQA/Script.pm
/usr/share/openqa/lib/OpenQA/ServerSideDataTable.pm
/usr/share/openqa/lib/OpenQA/Setup.pm
/usr/share/openqa/lib/OpenQA/Shared/Controller/Auth.pm
/usr/share/openqa/lib/OpenQA/Shared/Plugin/Helpers.pm
/usr/share/openqa/lib/OpenQA/Task/Asset/Download.pm
/usr/share/openqa/lib/OpenQA/Task/Asset/Limit.pm
/usr/share/openqa/lib/OpenQA/Task/Iso/Schedule.pm
/usr/share/openqa/lib/OpenQA/Task/Job/Limit.pm
/usr/share/openqa/lib/OpenQA/Task/Needle/Delete.pm
/usr/share/openqa/lib/OpenQA/Task/Needle/Save.pm
/usr/share/openqa/lib/OpenQA/Task/Needle/Scan.pm
/usr/share/openqa/lib/OpenQA/Task/Screenshot/Scan.pm
/usr/share/openqa/lib/OpenQA/UserAgent.pm
/usr/share/openqa/lib/OpenQA/Utils.pm
/usr/share/openqa/lib/OpenQA/WebAPI.pm
/usr/share/openqa/lib/OpenQA/WebAPI/AssetPipe.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Auth/Fake.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Auth/OpenID.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Auth/iChain.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Command/gru.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Command/gru/list.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Command/gru/run.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Asset.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Bug.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Command.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Comment.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Feature.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Iso.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Job.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/JobGroup.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/JobTemplate.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Locks.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Mm.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Table.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/API/V1/Worker.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/Asset.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/AuditLog.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/Influxdb.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/JobGroup.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/JobTemplate.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/Machine.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/Needle.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/Product.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/Table.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/TestSuite.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/User.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Admin/Workers.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/ApiKey.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Developer.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/File.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/LiveViewHandler.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Main.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Running.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Session.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Step.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Controller/Test.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Description.pm
/usr/share/openqa/lib/OpenQA/WebAPI/GruJob.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/AMQP.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/AuditLog.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/CSRF.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/Fedmsg.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/Gru.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/HashedParams.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/Helpers.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/MemoryLimit.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/ObsRsync.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/ObsRsync/Controller.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_folder.html.ep
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_index.html.ep
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_logfiles.html.ep
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/ObsRsync/templates/ObsRsync_logs.html.ep
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/REST.pm
/usr/share/openqa/lib/OpenQA/WebAPI/Plugin/YAMLRenderer.pm
/usr/share/openqa/lib/OpenQA/WebSockets.pm
/usr/share/openqa/lib/OpenQA/WebSockets/Client.pm
/usr/share/openqa/lib/OpenQA/WebSockets/Controller/API.pm
/usr/share/openqa/lib/OpenQA/WebSockets/Controller/Worker.pm
/usr/share/openqa/lib/OpenQA/WebSockets/Model/Status.pm
/usr/share/openqa/lib/OpenQA/WebSockets/Plugin/Helpers.pm
/usr/share/openqa/lib/OpenQA/Worker.pm
/usr/share/openqa/lib/OpenQA/Worker/Cache.pm
/usr/share/openqa/lib/OpenQA/Worker/Cache/Client.pm
/usr/share/openqa/lib/OpenQA/Worker/Cache/Request.pm
/usr/share/openqa/lib/OpenQA/Worker/Cache/Request/Asset.pm
/usr/share/openqa/lib/OpenQA/Worker/Cache/Request/Sync.pm
/usr/share/openqa/lib/OpenQA/Worker/Cache/Service.pm
/usr/share/openqa/lib/OpenQA/Worker/Cache/Task.pm
/usr/share/openqa/lib/OpenQA/Worker/Cache/Task/Asset.pm
/usr/share/openqa/lib/OpenQA/Worker/Cache/Task/Sync.pm
/usr/share/openqa/lib/OpenQA/Worker/CommandHandler.pm
/usr/share/openqa/lib/OpenQA/Worker/Engines/isotovideo.pm
/usr/share/openqa/lib/OpenQA/Worker/Job.pm
/usr/share/openqa/lib/OpenQA/Worker/Settings.pm
/usr/share/openqa/lib/OpenQA/Worker/WebUIConnection.pm
/usr/share/openqa/lib/perlcritic/Perl/Critic/Policy/ConsistentQuoteLikeWords.pm
/usr/share/openqa/lib/perlcritic/Perl/Critic/Policy/HashKeyQuotes.pm
/usr/share/openqa/public/favicon.ico
/usr/share/openqa/public/robots.txt
/usr/share/openqa/public/schema/JobTemplate.yaml
/usr/share/openqa/script/check_dependencies
/usr/share/openqa/script/client
/usr/share/openqa/script/clone_job.pl
/usr/share/openqa/script/configure-web-proxy
/usr/share/openqa/script/create_admin
/usr/share/openqa/script/dump_templates
/usr/share/openqa/script/fetchneedles
/usr/share/openqa/script/initdb
/usr/share/openqa/script/load_templates
/usr/share/openqa/script/modify_needle
/usr/share/openqa/script/openqa
/usr/share/openqa/script/openqa-bootstrap
/usr/share/openqa/script/openqa-bootstrap-container
/usr/share/openqa/script/openqa-clone-custom-git-refspec
/usr/share/openqa/script/openqa-clone-job
/usr/share/openqa/script/openqa-label-all
/usr/share/openqa/script/openqa-livehandler
/usr/share/openqa/script/openqa-scheduler
/usr/share/openqa/script/openqa-websockets
/usr/share/openqa/script/openqa-workercache
/usr/share/openqa/script/upgradedb
/usr/share/openqa/script/worker
/usr/share/openqa/templates/admin/api_help.html.ep
/usr/share/openqa/templates/admin/asset/index.html.ep
/usr/share/openqa/templates/admin/audit_log/event.html.ep
/usr/share/openqa/templates/admin/audit_log/index.html.ep
/usr/share/openqa/templates/admin/audit_log/productlog.html.ep
/usr/share/openqa/templates/admin/group/connect.html.ep
/usr/share/openqa/templates/admin/group/group_property_editor.html.ep
/usr/share/openqa/templates/admin/group/index.html.ep
/usr/share/openqa/templates/admin/group/job_group_row.html.ep
/usr/share/openqa/templates/admin/group/parent_group_property_editor.html.ep
/usr/share/openqa/templates/admin/group/parent_group_row.html.ep
/usr/share/openqa/templates/admin/job_template/index.html.ep
/usr/share/openqa/templates/admin/machine/index.html.ep
/usr/share/openqa/templates/admin/needle/index.html.ep
/usr/share/openqa/templates/admin/product/index.html.ep
/usr/share/openqa/templates/admin/test_suite/index.html.ep
/usr/share/openqa/templates/admin/user/index.html.ep
/usr/share/openqa/templates/admin/workers/index.html.ep
/usr/share/openqa/templates/admin/workers/show.html.ep
/usr/share/openqa/templates/admin/workers/worker_status.html.ep
/usr/share/openqa/templates/api_key/index.html.ep
/usr/share/openqa/templates/branding/openSUSE/docbox.html.ep
/usr/share/openqa/templates/branding/openSUSE/external_reporting.html.ep
/usr/share/openqa/templates/branding/openSUSE/sponsorbox.html.ep
/usr/share/openqa/templates/branding/openqa.suse.de/docbox.html.ep
/usr/share/openqa/templates/branding/openqa.suse.de/external_reporting.html.ep
/usr/share/openqa/templates/branding/openqa.suse.de/sponsorbox.html.ep
/usr/share/openqa/templates/branding/plain/docbox.html.ep
/usr/share/openqa/templates/branding/plain/sponsorbox.html.ep
/usr/share/openqa/templates/comments/add_comment_form_groups.html.ep
/usr/share/openqa/templates/comments/comment_row.html.ep
/usr/share/openqa/templates/comments/pagination.html.ep
/usr/share/openqa/templates/developer/ws_console.html.ep
/usr/share/openqa/templates/exception.html.ep
/usr/share/openqa/templates/layouts/bootstrap.html.ep
/usr/share/openqa/templates/layouts/error.html.ep
/usr/share/openqa/templates/layouts/info.html.ep
/usr/share/openqa/templates/layouts/navbar.html.ep
/usr/share/openqa/templates/main/build_progressbar.html.ep
/usr/share/openqa/templates/main/changelog.html.ep
/usr/share/openqa/templates/main/comment_area.html.ep
/usr/share/openqa/templates/main/group_builds.html.ep
/usr/share/openqa/templates/main/group_overview.html.ep
/usr/share/openqa/templates/main/index.html.ep
/usr/share/openqa/templates/main/more_builds.html.ep
/usr/share/openqa/templates/main/parent_group_overview.html.ep
/usr/share/openqa/templates/main/pinned_comments.html.ep
/usr/share/openqa/templates/main/review_badge.html.ep
/usr/share/openqa/templates/main/specific_not_found.html.ep
/usr/share/openqa/templates/not_found.html.ep
/usr/share/openqa/templates/step/edit.html.ep
/usr/share/openqa/templates/step/src.html.ep
/usr/share/openqa/templates/step/src.txt.ep
/usr/share/openqa/templates/step/viewaudio.html.ep
/usr/share/openqa/templates/step/viewimg.html.ep
/usr/share/openqa/templates/step/viewtext.html.ep
/usr/share/openqa/templates/test/comments.html.ep
/usr/share/openqa/templates/test/dependencies.html.ep
/usr/share/openqa/templates/test/details.html.ep
/usr/share/openqa/templates/test/downloads.html.ep
/usr/share/openqa/templates/test/external.html.ep
/usr/share/openqa/templates/test/infopanel.html.ep
/usr/share/openqa/templates/test/job_next_previous.html.ep
/usr/share/openqa/templates/test/list.html.ep
/usr/share/openqa/templates/test/live.html.ep
/usr/share/openqa/templates/test/module_components.html.ep
/usr/share/openqa/templates/test/module_select.html.ep
/usr/share/openqa/templates/test/module_table.html.ep
/usr/share/openqa/templates/test/overview.html.ep
/usr/share/openqa/templates/test/overview_result_table.html.ep
/usr/share/openqa/templates/test/result.html.ep
/usr/share/openqa/templates/test/settings.html.ep
/usr/share/openqa/templates/test/tr_job_result.html.ep
/usr/share/openqa/templates/test/tr_job_result_details.html.ep
/usr/share/openqa/templates/test/tr_job_result_failedmodules.html.ep

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/openQA/COPYING

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/openqa-gru.service
/usr/lib/systemd/system/openqa-livehandler.service
/usr/lib/systemd/system/openqa-scheduler.service
/usr/lib/systemd/system/openqa-setup-db.service
/usr/lib/systemd/system/openqa-slirpvde.service
/usr/lib/systemd/system/openqa-vde_switch.service
/usr/lib/systemd/system/openqa-websockets.service
/usr/lib/systemd/system/openqa-webui.service
/usr/lib/systemd/system/openqa-worker-cacheservice-minion.service
/usr/lib/systemd/system/openqa-worker-cacheservice.service
/usr/lib/systemd/system/openqa-worker-no-cleanup@.service
/usr/lib/systemd/system/openqa-worker.target
/usr/lib/systemd/system/openqa-worker@.service
